### ISSUE TITLE
Export the IP address after the resource is created

### ISSUE THREAD

**Issue by alexandrujieanu** [Ouest-France/terraform-provider-phpipam#21]
Hello,

I am using this provider to create some addresses in PHPIPAM, then I am creating some virtual machines with the IP address.
Basically, the `resource "phpipam_address"` creates  the IP address, then I need another resource to use it.

This worked fine while I specified the IP address and used it both to create the entry in IPAM and to create my vms.
Not specifying `ip_address` in `resource "phpipam_address"` gives me a free IP address, but I can't pass it to another resource.

Can this be done? I checked the [PHPIPAM API ](https://phpipam.net/#addresses), but it doesn't say which attributes are returned in the response.

Thank you a lot!

**Comment by pablo-ruth** [comment]
Hello,

I'm out of office so I can't test but you should get the value of ip_address from the phpipam_address resource:

```
resource "phpipam_address" "free" {
  subnet_id = 3
  hostname  = "test.mydomain.com"
}

output "ip_address" {
  value = phpipam_address.free.ip_address
}
```

**Comment by alexandrujieanu** [comment]
Thanks, I'll try this.

**Comment by alexandrujieanu** [comment]
@pablo-ruth 

I faced this again while refactoring my phpipam module. It turns out the `phpipam_address` exports `ip_address`, but this is not mentioned in the [attribute reference](https://registry.terraform.io/providers/Ouest-France/phpipam/latest/docs/resources/address#attribute-reference). 

For example the [aws_instance resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#attributes-reference) mentions `In addition to all arguments above, the following attributes are exported`. In case of the `phpipam_address` resource the `ip_address` is optional so it's not obvious to me that it can be exported.

Otherwise the provider works great. I use it as a source of truth for Terraform. Thanks.
