### ISSUE TITLE
Allow "insecure" ssl connection in provider

### ISSUE THREAD

**Issue by rhys-evans** [Ouest-France/terraform-provider-phpipam#28]
We have self signed ssl certs, that this provider does not work with. We Ideally would like the option to enable this

**Comment by rhysxevans** [comment]
Without this we get ```"Error: Error logging into PHPIPAM: HTTP protocol error: Post "https://xxxxxxxx/phpipam/api/terraform/user/": x509: cannot validate certificate for xxxxxxxx because it doesn't contain any IP SANs"``` when using ips

**Comment by pablo-ruth** [comment]
Both PR are merged and a version 0.6.0 of the provider is released with the fix. Thanks for your contribution!

**Comment by rhys-evans** [comment]
Thanks
