### ISSUE TITLE
Get multiple free adresses

### ISSUE THREAD

**Issue by cospeedster** [Ouest-France/terraform-provider-phpipam#5]
Hello everyone,

first thank you @pablo-ruth for updating this provider! Can you help me to find out how I can get multiple free addresses in one subnet? I want to deploy machines with "count".

I thought that I have to use "phpipam_addresses" but the following example doesn't work for me:
```HCL
data "phpipam_addresses" "address_search" {
  subnet_id = 3
}

data "phpipam_address" "addresses" {
  count      = "${length(data.phpipam_addresses.address_search.address_ids)}"
  address_id = "${element(data.phpipam_addresses.address_search.address_ids, count.index)}"
}

output "ip_addresses" {
  value = ["${data.phpipam_address.addresses.*.ip_address}"]
}
```
I got:
```bash
$ terraform apply
data.phpipam_addresses.address_search: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

ip_addresses = [
  [],
]
```

Do you have any examples or ideas for me?

Best regards

**Comment by pablo-ruth** [comment]
Hello,

You should use the phpipam_address resource in place of the datasource. The resource gets the first free ip address and reserves it in an atomic way, but the datasource only get the next free one and since it doesn't reserve it it's always the same ip that is returned.

Example:
```terraform
resource "phpipam_address" "addresses" {
  count = 5

  subnet_id = 3
  hostname  = "vm0${count.index}.mydomain.com"
}

output "ip_addresses" {
  value = ["${phpipam_address.addresses.*.ip_address}"]
}
```

**Comment by cospeedster** [comment]
Thank you very much! This worked for me. I thought I have to provide the address to the phpipam_address resource.
